version: '3'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      - "5678:5678"  # Debug port
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_APP=app.py
      - DATABASE_URL=postgresql://user:password@db:5432/sellscalehood
    depends_on:
      - db
    restart: unless-stopped
    command: ["sh", "-c", "pip install debugpy -t /tmp && python -m flask run --host=0.0.0.0 --port=5001"]


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${FRONTEND_TARGET:-development}
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001
      - CHOKIDAR_USEPOLLING=true
      - PORT=${FRONTEND_PORT:-3000}
    depends_on:
      - backend
    stdin_open: true
    tty: true

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sellscalehood
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    name: app_network